### Получение рецептов
GET http://localhost:8080/recipe
### Создание нового рецепта
POST http://localhost:8080/recipe
Content-Type: application/json

{
    "title": "Сырники из творога",
    "cookingTime": "30 минут",
    "ingredients": [
      {
        "name": "Творог",
        "weight": 350,
        "unitOfMeasurement": "г."
      },
      {
        "name": "Куриное яйцо",
        "weight": 2,
        "unitOfMeasurement": "шт"
      },
      {
        "name": "Пшеничная мука",
        "weight": 6,
        "unitOfMeasurement": "столовых ложек"
      },
      {
        "name": "Сахар",
        "weight": 2,
        "unitOfMeasurement": "столовые ложки"
      }
    ],
    "cookingInstructions":[
      {
        "step": "1", "name" : "Смешайте весь творог с яйцами, сахаром и тщательно всё перемешайте."
      },
      {
        "step": "2", "name" : "Всыпьте в творог муку и тщательно перемешайте. "
      },
      {
        "step": "3", "name" : "Поставьте сковороду на средний огонь и налейте в нее подсолнечное масло."
      },
      {
        "step": "4", "name" : "Слепите несколько небольших шариков из получившейся творожной массы и положите их на тарелку. Затем по очереди обкатывайте творожные шарики в муке и выкладывайте на сковороду."
      },
      {
        "step": "5", "name" : "Обжаривайте сырники 1–2 минуты до появления золотистой корочки. Затем переверните их на другую сторону и также обжарьте до золотистого состояния."
      },
      {
        "step": "6",
        "name": "Повторяйте, пока творог не закончится."
      }
      ]
}

### Создание нового рецепта 2
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "title": "Салат из красной фасоли с творожным сыром, красным луком и сезонным салатом ",
  "cookingTime": "7 минут",
  "ingredients": [
    {
      "name": "Специи",
      "weight": 0,
      "unitOfMeasurement": "по вкусу"
    },
    {
      "name": "Консервированная фасоль",
      "weight": 400,
      "unitOfMeasurement": "г."
    },
    {
      "name": "Лимон",
      "weight": 1,
      "unitOfMeasurement": "штука"
    },
    {
      "name": "Чеснок",
      "weight": 2,
      "unitOfMeasurement": "зубчика"
    },
    {
      "name": "Оливковое масло ",
      "weight": 50,
      "unitOfMeasurement": "мл."
    },
    {
      "name": "Рукола",
      "weight": 100,
      "unitOfMeasurement": "г."
    },
    {
      "name": "Творожный сыр",
      "weight": 200,
      "unitOfMeasurement": "г."
    },
    {
      "name": "Красный лук",
      "weight": 50,
      "unitOfMeasurement": "г."
    }
  ],
  "cookingInstructions": [
    {
      "step": "1", "name" : "Открыть две банки красной фасоли в собственном соку, слить сок и промыть фасоль холодной водой. "
    },
    {
      "step": "2", "name" : "Готовую фасоль смешать с мелко нарубленным красным луком, зеленью, давленым чесноком, оливковым маслом, лимонным соком и творожным сыром."
    },
    {
      "step": "3", "name" : "Посолить, поперчить, дать продуктам две минуты притереться друг к другу и подавать к столу."
    }
  ]
}

### Создание нового рецепта 3
POST http://localhost:8080/recipe
Content-Type: application/json

{
"title": "Чечевичный суп с мятой ",
"cookingTime": "30 минут.",
"ingredients": [
{
"name": "Красная чечевица",
"weight": 150,
"unitOfMeasurement": "г."
},
{
"name": "Репчатый лук",
"weight": 1,
"unitOfMeasurement": "головка"
},
{
"name": "Морковь",
"weight": 1,
"unitOfMeasurement": "штука"
},
{
"name": "Подсолнечное масло",
"weight": 30,
"unitOfMeasurement": "мл."
},
{
"name": "Сливочное масло",
"weight": 15,
"unitOfMeasurement": "г."
},
{
"name": "Пшеничная мука",
"weight": 30,
"unitOfMeasurement": "г."
},
{
"name": "Сливки 33% ",
"weight": 50,
"unitOfMeasurement": "мл."
},
{
"name": "Специи",
"weight": 0,
"unitOfMeasurement": "по вкусу"
},
{
"name": "Лимон",
"weight": 1.2,
"unitOfMeasurement": "штуки"
},
{
"name": "Мята",
"weight": 0,
"unitOfMeasurement": "по вкусу"
}
],
"cookingInstructions": [
{
"step": "1", "name" : "В небольшую кастрюлю налить литр воды и засыпать промытую чечевицу. Поставить кастрюлю на средний огонь."
},
{
"step": "2", "name" : "Натереть небольшую морковь на крупной терке, мелко нарезать лук. Как только чечевица начнет кипеть, надо убавить огонь, а затем долить еще 200 мл воды или бульона. Варить еще десять минут."
},
{
"step": "3", "name" : "Разогреть широкую плоскую сковороду, добавить туда подсолнечное и сливочное масло. Обжарить лук и морковь. "
},
{
"step": "4", "name" : "Добавить обжаренные овощи в кастрюлю, влить сливки. Взбить суп ручным блендером, чтобы он превратился в густое пюре. Суп можно подавать к столу. "
}
]
}

### Создание нового рецепта 4
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "title": "Салат с креветками и кунжутом",
  "cookingTime": "20 минут.",
  "ingredients": [
    {
      "name": "Помидоры",
      "weight": 3,
      "unitOfMeasurement": "штуки"
    },
    {
      "name": "Королевские креветки",
      "weight": 300,
      "unitOfMeasurement": "г."
    },
    {
      "name": "Зеленый салат",
      "weight": 1,
      "unitOfMeasurement": "пучок"
    },
    {
      "name": "Огурцы",
      "weight": 2,
      "unitOfMeasurement": "штуки"
    },
    {
      "name": "Специи",
      "weight": 0,
      "unitOfMeasurement": "по вкусу"
    },
    {
      "name": "Майонез",
      "weight": 0,
      "unitOfMeasurement": "по вкусу"
    },
    {
      "name": "Кунжутные семечки",
      "weight": 3,
      "unitOfMeasurement": "столовые ложки"
    }
  ],
  "cookingInstructions": [
    {
      "step": "1", "name" : "Порезать овощи крупно, салат порвать на куски."
    },
    {
      "step": "2", "name" : "Довести до кипения сильно соленую воду и добавить креветки. После кипения варить 5 минут."
    },
    {
      "step": "3", "name" : "Очистить креветки от панциря."
    },
    {
      "step": "4", "name" : "Смешать овощи и креветки."
    },
    {
      "step": "5", "name" : "Посыпать кунжутными семечками и заправить майонезом."
    }
  ]
}

### Создание нового рецепта 4
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "title": "Творожные пончики в сахарной пудре",
  "cookingTime": "40 минут.",
  "ingredients": [
    {
      "name": "Творог",
      "weight": 250,
      "unitOfMeasurement": "г."
    },
    {
      "name": "Куриное яйцо",
      "weight": 3,
      "unitOfMeasurement": "штуки"
    },
    {
      "name": "Пшеничная мука",
      "weight": 8,
      "unitOfMeasurement": "столовых ложек"
    },
    {
      "name": "Сахар и соль",
      "weight": 0,
      "unitOfMeasurement": "по вкусу"
    },
    {
      "name": "Оливковое масло",
      "weight": 0,
      "unitOfMeasurement": "по вкусу"
    },
    {
      "name": "Сода",
      "weight": 1.2,
      "unitOfMeasurement": "чайные ложки"
    },
    {
      "name": "Сахарная пудра с ванилью",
      "weight": 0,
      "unitOfMeasurement": "по вкусу"
    }
  ],
  "cookingInstructions": [
    {
      "step": "1", "name" : "В миске смешать творог, яйца, муку, сахар, соду и соль до однородной консистенции."
    },
    {
      "step": "2", "name" : "В небольшом сотейнике оливковое масло хорошо разогреть."
    },
    {
      "step": "3", "name" : "При помощи чайной ложки или руками скатать из теста шарики, каждый размером чуть меньше грецкого ореха."
    },
    {
      "step": "4", "name" : "Бросить пончики в кипящее масло и жарить на небольшом огне, постоянно переворачивая шумовкой."
    },
    {
      "step": "5", "name" : "Готовые пончики выложить на бумажное полотенце и оставить на одну-две минуты — чтобы оно впитало лишнее масло. Подавать пончики горячими, выложив на блюдо и посыпав сахарной пудрой, смешанной с ванилином."
    }
  ]
}
### Удаление рецепта
DELETE http://localhost:8080/recipe/
